[build]
  command = "npx @xyd-js/cli build"
  publish = ".xyd/build/client"
  
[[redirects]]
  from = "/"
  to = "/introduction/"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/introduction/"
  status = 301
  force = true
